### ISSUE TITLE
POST /profile/patient/appointments returns 500

### ISSUE THREAD

**Issue by pA1nD** [iHub-PTI/ihub-core#17]
Calling the endpoint returns internal server error. I've been using this payload:

```
{
    "start":"2020-11-08T17:39",
    "end":"2020-11-08T17:45",
    "doctorId": "152"
}
```

**Comment by rubenlop88** [comment]
Testing the endpoint with this specific values `"start":"2020-11-08T17:39", "end":"2020-11-08T17:45"` returns 400 Bad Request with an error message. Using valid date values, it returns 200 OK. Maybe it is an error in the Kong API Gateway.

**Comment by walter-bd** [comment]
I don't think that is the case, because if it was indeed kong it would return a 401 Unauthorized or a 502 Bad Gateway, not a 500 Internal Server Error. I think that error appears because a non-existing patient was used and the server tried to get the appointments for that user, giving a null pointer error.
